# Use node image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY src/ .

# Expose port
EXPOSE 5000

# Start server
CMD ["node", "server.js"]

